Add Comprehensive Codebase Documentation
TharunKumarrA/FC-TeamForge pull request #25
Opened 2024-12-29 10:10 UTC by that-ar-guy

fixes: #20 

**Description:**
This PR adds detailed documentation for the FC-TeamForge project in the `Docs/Codebase.md` file. The documentation provides an in-depth overview of the project structure, frontend and backend functionalities, interaction flow, and setup instructions. It aims to make the codebase easier to understand and contribute to, especially for new developers.

Changes:

1. Created Docs/Codebase.md:

      - Added a high-level overview of the project architecture (frontend and backend).
      - Documented the folder structure and explained the purpose of each key file, including index.html and Vue components like App.vue and NewPlayer.vue.
      - Detailed API endpoints and database operations in the backend.
      - Provided step-by-step setup instructions for both the frontend and backend.
      - Described the interaction flow between the frontend, backend, and database.

2025-01-03 17:04 UTC, TharunKumarrA requested changes
There is an exhaustive Backend integration documentation set up by another contributor Vivek, Can you see to it and attach that too (giving credits to him would be great in the docs)

2025-01-03 17:08 UTC, TharunKumarrA commented
I'm really sorry @that-ar-guy, I missed this pr in other ones, and made you wait for 5 days. This was a fault on my side, apologies. Great work man, just one change, see into it and we can merge it
✌🏽

2025-01-03 17:40 UTC, that-ar-guy commented
> There is an exhaustive Backend integration documentation set up by another contributor Vivek, Can you see to it and attach that too (giving credits to him would be great in the docs)

So vivek means him ? @thecodingvivek

2025-01-03 19:47 UTC, TharunKumarrA commented
Yes

2025-01-04 11:42 UTC, that-ar-guy commented
alright on it

2025-01-04 12:28 UTC, that-ar-guy commented
hey @TharunKumarrA , I've added the credits for [vivek](https://github.com/thecodingvivek) for the  backend integration guide along with his GitHub link; awaiting your review and the bounty update. Thank you!.

2025-01-05 02:43 UTC, Ashrockzzz2003 commented
@that-ar-guy 
We're sorry. The bounty points are purely meant for students from Amrita Vishwa Vidyapeetham, Coimbatore. It's an internal contest that's happening. The bounties are maintained on a leaderboard where only registered students are rewarded. Only if you're an Amrita student, the bounties will even reflect as they're all connected.

We're sorry if there was some confusion regarding the bounty! Anyway thanks for the contribution, it'll be merged after it's finalized and it'll be counted on `GitHub` as a `PR` and a valid open-source contribution for you! This will help you in your Open Source exploration too!

Thanks for the contribution @that-ar-guy.

2025-01-05 12:16 UTC, that-ar-guy commented
@Ashrockzzz2003  no problem...
but can i still contribute ...

2025-01-05 12:23 UTC, TharunKumarrA commented
Yes @that-ar-guy you can still contribute.
Thank you for understanding and sorry for the confusion 🙏

2025-01-05 12:24 UTC, Ashrockzzz2003 commented
Yess!
You can contribute @that-ar-guy!

2025-01-05 12:53 UTC, that-ar-guy commented
> Yes @that-ar-guy you can still contribute. Thank you for understanding and sorry for the confusion 🙏

No Problem
Just a suggestion: it would be great to include a note in the README.md files of all repositories participating in the `AMWOC` competition. This note should clearly state that the bounties are exclusively meant for the competition.

Since the repositories are public, they may attract a variety of contributors who might not be aware of the competition context. Adding this clarification will help avoid any confusion and set the right expectations for everyone.

Also, wishing you the very best for the competition you're hosting/conducting! It's amazing to see initiatives like this that encourage contributions and community engagement. Keep up the great work! 🎉💪

2025-01-05 13:04 UTC, TharunKumarrA commented
Thank you so much @that-ar-guy .
Yes that's a great suggestion from your side. Although we have a AMWOC tag attached to the issue people might not be familiar with what that is, so your suggestion would help a lot.
Thank you man

2025-01-05 18:12 UTC, TharunKumarrA approved these changes
LGTM 🚀

2025-01-05 18:12 UTC, merged